apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-frontend-deployment
spec:
  selector:
    matchLabels:
      app: site-frontend
  replicas: 2 
  template:
    metadata:
      labels:
        app: site-frontend
    spec:
      containers:
      - name: alex-site-frontend
        image: {{AWS_ECR_REPOSITORY}}/alexsite-frontend:latest
        ports:
        - containerPort: 80
