kind: Service
apiVersion: v1
metadata:
  name: site-frontend-service
spec:
  type: NodePort
  selector:
    app: site-frontend
  ports:
  - protocol: TCP
    #The first port is the one that is exposed to the K8s cluster internally
    #The targetPort is the port that the application exposes. 
    port: 8082
    targetPort: 80
    nodePort: 31706
